# See https://config.travis-ci.com/ for a full list of configuration options.

os: linux

dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - ./configure

script:
  - tmp/bin/pytest
